Redesign 0.8.0
Drill4J/test2code-ui pull request #131
Opened 2022-01-28 07:08 UTC by IliaSolovev

2022-02-01 23:01 UTC, RomanAchilov requested changes

2022-02-01 23:01 UTC, RomanAchilov commented on src/components/breadcrumbs/breadcrumbs.tsx
> +        const link = prepareLink(rawLink);
link = prepareLink(`${adminPath}${prepareLink(crumb.path)}`) mb?

2022-02-01 23:01 UTC, RomanAchilov commented on src/components/breadcrumbs/breadcrumbs.tsx
> +  :last-child {
https://tailwindcss.com/docs/hover-focus-and-other-states

2022-02-01 23:01 UTC, RomanAchilov commented on src/components/breadcrumbs/breadcrumbs.tsx
> +  :not(:first-child):before {
https://github.com/ben-rogerson/twin.macro
![Uploading Screenshot_2022-02-02-01-56-10-16_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

2022-02-01 23:01 UTC, RomanAchilov commented on src/components/breadcrumbs/breadcrumbs.tsx
> +const replaceLinkValues = ({ buildVersion, scopeId }: {buildVersion: string, scopeId: string}) =>
Gl hf

2022-02-01 23:01 UTC, RomanAchilov commented on src/pages/agent/build-overview/build-overview.tsx
> +          active={!activeTab || activeTab === "methods"}
Active not active tab 🙂

2022-02-02 08:43 UTC, IliaSolovev commented
rebase

2022-03-18 07:02 UTC, merged