feat: add setPanel func to session managment panel
Drill4J/test2code-ui pull request #141
Opened 2022-02-24 15:25 UTC by dmitrii-kliushentsev

2022-02-25 06:51 UTC, IliaSolovev requested changes

2022-02-25 06:51 UTC, IliaSolovev commented on src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
> +import { SetPanelContext } from "../../../Drill4J-test-to-code";
create file with context and use alias

2022-02-25 06:51 UTC, IliaSolovev commented on src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
> +import { useAdminConnection, useAgent } from "../../../hooks";
alias

2022-02-25 06:51 UTC, IliaSolovev commented on src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
> +  const agent = useAgent(agentId);
i think that we already have this data it parent component. Check it

2022-02-25 06:51 UTC, IliaSolovev commented on src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
> +  const linkToSettingsHandler = () => {
separate this function into two functions for Agent and Group. You can create it in jsx because it won`t affect performance

2022-02-25 06:51 UTC, IliaSolovev commented on src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
> +        payload: { ...agent, tab: "system" },
Why we don`t pass agentType here

2022-03-09 06:41 UTC, IliaSolovev requested changes

2022-03-09 06:41 UTC, IliaSolovev commented on src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
> +  agent: Agent;
Why agent you will recieve everywhen but group can be null sometimes

2022-03-09 06:41 UTC, IliaSolovev commented on src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
> +                onClick={() => {
You don`t need braces here

2022-03-09 06:41 UTC, IliaSolovev commented on src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
> +                    payload: { ...agent, tab: "system" },
Are you sure that you should open system tab? It`s from the spec?

2022-03-09 06:41 UTC, IliaSolovev commented on src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
> +                    payload: { ...Object(group), agentType: "Group", tab: "system" },
What do you try to do this constuction?

2022-03-10 00:05 UTC, dmitrii-kliushentsev commented on src/modules/sessions-management-pane/management-new-session/management-new-session.tsx
> +                onClick={() => {
ts lint error

2022-03-14 07:14 UTC, IliaSolovev approved these changes

2022-03-14 08:56 UTC, merged