EPMDJ-9248: Add name for all tables
Drill4J/test2code-ui pull request #94
Opened 2021-12-08 12:15 UTC by dmitrii-kliushentsev

2021-12-10 10:13 UTC, RomanAchilov requested changes

2021-12-10 10:13 UTC, RomanAchilov commented on src/pages/agent/methods-table/methods-table.tsx
> +        {...renderProps}
```suggestion
    renderheader={(props) => <Component {...props}/>}
```

2021-12-10 10:13 UTC, RomanAchilov commented on src/pages/agent/tests-table/test-details.tsx
> +    <div tw="flex flex-col pt-8" data-test="test-details:table-wrapper">
mt

2021-12-13 06:54 UTC, IliaSolovev requested changes

2021-12-13 06:54 UTC, IliaSolovev commented on src/pages/agent/tests-to-run/tests-to-run.tsx
> +                <div />
remove

2021-12-14 08:53 UTC, IliaSolovev approved these changes

2021-12-14 08:53 UTC, IliaSolovev commented on src/pages/agent/tests-to-run/tests-to-run.tsx
> +                <div />
```suggestion
               
```

2021-12-14 10:39 UTC, merged